name: base

train:
  hflip: True
  vflip: True
  random_scale: 0.0
  random_rotate: 90.0
  color_jitter:
    brightness: 0.0
    contrast: 0.0
    saturation: 0.0
    hue: 0.0
  resize: 256
  random_crop: 256
  gaussian_blur: 0.0
  gaussian_noise: 0.0

  
val:
  resize: 256

