head: fpn
backbone: mit_b3

n_classes: 2
class_names: 
  - Background
  - in_focus

metric_classes:
  - in_focus

encoder_weights: null
encoder_weights_path: /scratch0/f89601470/torch/hub/checkpoints/mit_b3.pth
